### ISSUE TITLE
Responsive H1 issue

### ISSUE THREAD

**Issue by TicklishGiraffe** [LTVFD/LTVFD_Website#6]
H3 was changed to H1 in the header, with changes to make it more responsive.
Now does not generate properly

**Comment by TicklishGiraffe** [comment]
Note- works fine in testing, when brought live it crashes out. Suggest switching back to H3?

**Comment by ciscogallery** [comment]
http://test.lebanontownshipfire.org/ shows it working correctly. What browser are you using?

**Comment by TicklishGiraffe** [comment]
Tested it on Chrome and Firefox, both had it

**Comment by ciscogallery** [comment]
Both are working correctly on my computer, maybe try clearing your cache?

**Comment by ciscogallery** [comment]
Can you screenshot the issue?

**Comment by TicklishGiraffe** [comment]
[screenshot.docx](https://github.com/LTVFD/LTVFD_Website/files/831827/screenshot.docx)

**Comment by TicklishGiraffe** [comment]
Clearing my cache worked...
Just kidding. PROBLEM SOLVED!
