### ISSUE TITLE
Correct Contact Us and Footer backgrounds

### ISSUE THREAD

**Issue by ciscogallery** [LTVFD/LTVFD_Website#7]
Please make the Contact Us background the color that the footer is now (so that it doesn't look like it's the same section as the apparatus), then darken the footer background.

**Comment by TicklishGiraffe** [comment]
Done, but I took a liberty with the footer and went further than just darkening it.  A creative choice if I may say so myself but needs design permission.  Its in the dev for now, if you like it as that we can close this issue.

**Comment by ciscogallery** [comment]
I like the blue, but let's make the facebook and github icons white now :)

**Comment by TicklishGiraffe** [comment]
Survey Says! (See poll on slack to decide button color)
